django/Taskapp/Taskapp/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("todo.urls"))
]

django/Taskapp/todo/urls.py
from django.urls import path
from . import views

app_name = "todo"
urlpatterns = [
    path('', views.main, name="main"),
    path('add/', views.add, name="add")
]

django/Taskapp/todo/models.py
from django.db import models

# Create your models here.

django/Taskapp/todo/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django import forms
from django.http import HttpResponseRedirect
from django.urls import reverse
# Create your views here.

tasks = ["Hello"]


class NewTaskForm(forms.Form):
    task = forms.CharField(label="TaskName")


def main(request):

    return render(request, 'main.html', {
        "tasks": tasks
    })


def add(request):
    if request.method == "POST":
        form = NewTaskForm(request.POST)
        if form.is_valid():
            task = form.cleaned_data["task"]
            tasks.append(task)
            return HttpResponseRedirect(reverse("tasks:main"))
        else:
            return render(request, "addtask.html", {
                "form": form
            })

    return render(request, 'addtask.html', {
        "form": NewTaskForm()
    })

django/Taskapp/todo/templates/addtask.html
{% extends "layout.html" %}
{% block head %}
    {% load static%}
    <link rel="stylesheet" href="{% static 'css/addtask.css' %}">
{% endblock %}

{% block body %}
    <p>Add Tasks✔✔✔</p>

    <form action="{% url 'todo:main' %}" method="post">
        {% csrf_token %}
        {{form}}
        <input type="submit">
    </form>
    <br/>
    <a href="{% url 'todo:main' %}">View Tasks</a>

{% endblock %}

django/Taskapp/todo/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Todo App</title>
    {% block head %}

    {% endblock %}
</head>
<body>
    {% block body %}

    {% endblock %}
</body>
</html>

django/Taskapp/todo/templates/main.html
{% extends "layout.html" %}
{% block head %}
    {% load static%}
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
{% endblock %}

{% block body %}
    <h1>🚀Welcome To Thasa's Todo App✔</h1>
    <a href="{% url 'todo:add' %}">Add Task</a>
    <ul>
        {% for task in tasks %}
            <li>{{task}}</li>
            {% empty %}
            <li>No task Yet!</li>
        {% endfor %}
        
    </ul>
{% endblock %}